const mongoose=require('mongoose')
module.exports={
    userSchema:new mongoose.Schema({
        username:{
            type:String,
            required:true
        },
        phone:{
            type:Number,
            required:true
        },
        email:{
            type:String,
            required:true
        },
        gender:{
            type:String,
            required:true
        },
        password:{
            type:String,
            required:true
        },
        status:{
            type:Boolean,
            required:true
        }
    }),
    adminSchema:new mongoose.Schema({
        username:{
            type:String,
            required:true
        },
        email:{
            type:String,
            required:true
        },
        password:{
            type:String,
            required:true
        }
    }),
    productSchema:new mongoose.Schema({
        product:{
            type:String,
            required:true
        },
        brabd:{
            type:String,
            required:true
        },
        price:{
            type:Number,
            required:true
        },
        category:{
            type:String,
            required:true
        },
        stock:{
            type:Number,
            required:true
        },
        rating:{
            type:Number,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        discount:{
            type:Number,
            required:true
        },
        Images:{
            type:Array,
            required:true 
        },
        size:{
            type:Array,
            required:true
        }

    }),
    categorySchema:new mongoose.Schema({
        category:{
            type:String,
            required:true
        }
    }),
    cartSchema:new mongoose.Schema({
        user:{
            type:String,
            required:true
        },
        products:{
            typeof:Array
        }
    })
}